# Permalinks
permalink:           pretty

# Setup
title:               Andrea Gao
tagline:             'Data Science, Duke, Bayes'
url:                 http://gytcrt.github.io
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Andrea Gao
  url:
  email:             gaoyuantcrt@gmail.com

# Custom vars
version:             1.0.0
github:
  repo:

# This is the list of pages to include in the header of the website.
pages_list:
  About Me: '/about/'
  Archive: '/archive/'
  Life: '/life/'


# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
